FROM mysql:5.7

# ENV MYSQL_DATABASE reviewList
# ENV MYSQL_ROOT_PASSWORD supersecret
# ENV MYSQL_USER mysql
# ENV MYSQL_ROOT_PASSWORD supersecret
# ENV DATABASE_HOST db

EXPOSE 3306

COPY ./schema.sql /docker-entrypoint-initdb.d/